### ISSUE TITLE
`run_print_file` option not supported

### ISSUE THREAD

**Issue by lucifer1004** [dmckwski/MSTM#5]
It is still listed in the manual, but after searching the code, I could not find it anywhere.

**Comment by dmckwski** [comment]
Should be 'run_file'.    I will correct the manual.

**Comment by lucifer1004** [comment]
Fixed in the updated manual.

**Comment by SoulEater45** [comment]
In the manual as of [now, 2nd of June 2022](https://github.com/dmckwski/MSTM/blob/v4.0.0/doc/mstm-manual-2021.pdf), the `run_print_file` is still present and should probably be changed to the mentioned `run_file` option.
